# Nome do pipeline visível no GitHub
name: CI Calculadora

# Gatilhos: O que faz o pipeline rodar?
on: 
  workflow_dispatch: # 1. Botão de execução manual no GitHub
  pull_request: 
    branches: [dev] # 2. Automático ao receber código na branch 'dev'

# Lista de trabalhos a serem executados
jobs:
  ci: # Nome do nosso bloco de trabalho
    runs-on: ubuntu-latest # Servidor Linux zerado emprestado pelo GitHub
    
    # Passo a passo das tarefas dentro do servidor
    steps: 
      - name: Baixar o código
        uses: actions/checkout@v4 # Ação oficial que faz o "git clone" do projeto
        
      - name: Configurar o Python
        uses: actions/setup-python@v5 # Ação oficial que instala o ambiente Python
        with: 
          python-version: '3.13' # Especifica a versão exata do Python necessária
          
      - name: Instalar Dependências
        # O "run" abre o terminal do SERVIDOR UBUNTU do GitHub e digita os comandos abaixo
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Executar Testes
        # Roda o comando final no terminal do servidor para buscar e testar o código
        run: pytest