name: release
on:
  push:
    branches: [main]

permissions: 
  contents: write

jobs:
  liberar: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Baixar o código
        uses: actions/checkout@v4
        
      - name: Configurar o Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
          
      - name: Instalar Dependências
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Executar Testes
        run: pytest 
        
      - name: Criar Pacote Limpo (ZIP)
        run: |
          # 1. Cria uma pasta temporária vazia
          mkdir pacote_entrega
          
          # 2. Copia APENAS a pasta 'src' para dentro dela. 
          # Como o requirements.txt, o README e os arquivos do Git estão fora da 'src', 
          # eles já ficam para trás automaticamente aqui!
          cp -r src pacote_entrega/
          
          # 3. Caça e destrói qualquer pasta __pycache__ que o 'pytest' acabou de gerar
          find pacote_entrega -type d -name "__pycache__" -exec rm -rf {} +
          
          # 4. Entra na pasta limpa e gera o zip final
          cd pacote_entrega && zip -r ../calculadora.zip .

      - name: Criar Release no GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete v1.0.0 --yes || true
          
          # Cria a nova release com o ZIP limpo
          gh release create v1.0.0 calculadora.zip --title "Release v1.0.0" --notes "Versão oficial de produção sem arquivos de teste."


  deploy:
    name: Deploy para o Render
    needs: liberar # Regra de ouro: Só faz o deploy se a release (ZIP) foi criada com sucesso
    runs-on: ubuntu-latest
    
    steps:
      - name: Avisar o Render para atualizar a produção
        env:
          # Puxa a URL secreta do cofre do repositório
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        # O 'curl -X POST' é o comando de terminal para acessar o link e disparar o webhook
        run: |
          if [ -z "$DEPLOY_HOOK" ]; then
            echo "Erro: Webhook do Render não encontrado nos Secrets."
            exit 1
          fi
          curl -X POST $DEPLOY_HOOK